name: AntiforceOP
version: '${project.version}'
main: dev.merciful.main.AntiforceOP
api-version: 1.18
authors: [ Merciful ]
description: Only allows operators listed in the config.yml
commands:
  opreload:
    description: Reloads the config
    usage: /<command>
  op:
    description: overrides vanilla OP command